In [4]:
import numpy as np
A = np.random.random((3,4))
print(A)

[[0.40677597 0.20349087 0.47153835 0.03487452]
 [0.62750865 0.41805444 0.47017376 0.81863547]
 [0.6251257  0.82676178 0.81759628 0.14088195]]
